import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import bcrypt from "bcryptjs";
import * as dotenv from "dotenv";

dotenv.config();

// ─── Filamentos ───────────────────────────────────────────────────────────────

// ─── Entradas explícitas Bambu Lab (código único por material+cor) ───────────

interface FilamentEntry {
  brand: string;
  material: string;
  colorName: string;
  colorCode?: string;
  colorHex: string;
  spoolWeight: number;
  density?: number;
}

// Cada linha é uma SKU real do catálogo Bambu Lab.
// Código fonte: bambulab.com/filament
// Formato: XXXXX onde os primeiros 2 dígitos = família de material,
// os seguintes 3 = variante de cor.
const bambuEntries: FilamentEntry[] = [
  // ── PLA Basic (10xxx) ────────────────────────────────────────────────────
  {
    brand: "Bambu Lab",
    material: "PLA Basic",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "10100",
    colorName: "Jade White",
    colorHex: "#FAFAFA",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Basic",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "10101",
    colorName: "Black",
    colorHex: "#1A1A1A",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Basic",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "10102",
    colorName: "Gray",
    colorHex: "#8A8D8F",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Basic",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "10103",
    colorName: "Silver",
    colorHex: "#A2A5A4",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Basic",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "10200",
    colorName: "Red",
    colorHex: "#C82B2B",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Basic",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "10201",
    colorName: "Magenta",
    colorHex: "#CA3B6C",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Basic",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "10300",
    colorName: "Orange",
    colorHex: "#ED712A",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Basic",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "10400",
    colorName: "Yellow",
    colorHex: "#F5C71A",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Basic",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "10401",
    colorName: "Gold",
    colorHex: "#D6A34A",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Basic",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "10500",
    colorName: "Green",
    colorHex: "#40A040",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Basic",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "10501",
    colorName: "Bambu Green",
    colorHex: "#00AE42",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Basic",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "10600",
    colorName: "Cyan",
    colorHex: "#1F9EBA",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Basic",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "10601",
    colorName: "Blue",
    colorHex: "#2D4C8A",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Basic",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "10700",
    colorName: "Purple",
    colorHex: "#724996",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Basic",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "10701",
    colorName: "Pink",
    colorHex: "#F293B8",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Basic",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "10800",
    colorName: "Brown",
    colorHex: "#6B4C3A",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Basic",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "10801",
    colorName: "Bronze",
    colorHex: "#805B3A",
  },

  // ── PLA Matte (11xxx) ────────────────────────────────────────────────────
  {
    brand: "Bambu Lab",
    material: "PLA Matte",
    spoolWeight: 1000,
    density: 1.31,
    colorCode: "11100",
    colorName: "Ivory White",
    colorHex: "#FFFFFF",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Matte",
    spoolWeight: 1000,
    density: 1.31,
    colorCode: "11101",
    colorName: "Charcoal",
    colorHex: "#000000",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Matte",
    spoolWeight: 1000,
    density: 1.31,
    colorCode: "11102",
    colorName: "Ash Gray",
    colorHex: "#9B9EA0",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Matte",
    spoolWeight: 1000,
    density: 1.31,
    colorCode: "11103",
    colorName: "Bone White",
    colorHex: "#CBC6B8",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Matte",
    spoolWeight: 1000,
    density: 1.31,
    colorCode: "11104",
    colorName: "Nardo Gray",
    colorHex: "#757575",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Matte",
    spoolWeight: 1000,
    density: 1.31,
    colorCode: "11200",
    colorName: "Scarlet Red",
    colorHex: "#DE4343",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Matte",
    spoolWeight: 1000,
    density: 1.31,
    colorCode: "11201",
    colorName: "Sakura Pink",
    colorHex: "#E8AFCF",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Matte",
    spoolWeight: 1000,
    density: 1.31,
    colorCode: "11202",
    colorName: "Dark Red",
    colorHex: "#BB3D43",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Matte",
    spoolWeight: 1000,
    density: 1.31,
    colorCode: "11203",
    colorName: "Terracotta",
    colorHex: "#B15533",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Matte",
    spoolWeight: 1000,
    density: 1.31,
    colorCode: "11204",
    colorName: "Plum",
    colorHex: "#950051",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Matte",
    spoolWeight: 1000,
    density: 1.31,
    colorCode: "11300",
    colorName: "Mandarin Orange",
    colorHex: "#F99963",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Matte",
    spoolWeight: 1000,
    density: 1.31,
    colorCode: "11400",
    colorName: "Lemon Yellow",
    colorHex: "#F7D959",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Matte",
    spoolWeight: 1000,
    density: 1.31,
    colorCode: "11401",
    colorName: "Desert Tan",
    colorHex: "#E8DBB7",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Matte",
    spoolWeight: 1000,
    density: 1.31,
    colorCode: "11500",
    colorName: "Grass Green",
    colorHex: "#61C680",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Matte",
    spoolWeight: 1000,
    density: 1.31,
    colorCode: "11501",
    colorName: "Dark Green",
    colorHex: "#68724D",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Matte",
    spoolWeight: 1000,
    density: 1.31,
    colorCode: "11502",
    colorName: "Apple Green",
    colorHex: "#C2E189",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Matte",
    spoolWeight: 1000,
    density: 1.31,
    colorCode: "11600",
    colorName: "Marine Blue",
    colorHex: "#0078BF",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Matte",
    spoolWeight: 1000,
    density: 1.31,
    colorCode: "11601",
    colorName: "Ice Blue",
    colorHex: "#A3D8E1",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Matte",
    spoolWeight: 1000,
    density: 1.31,
    colorCode: "11602",
    colorName: "Dark Blue",
    colorHex: "#042F56",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Matte",
    spoolWeight: 1000,
    density: 1.31,
    colorCode: "11603",
    colorName: "Sky Blue",
    colorHex: "#56B7E6",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Matte",
    spoolWeight: 1000,
    density: 1.31,
    colorCode: "11700",
    colorName: "Lilac Purple",
    colorHex: "#AE96D4",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Matte",
    spoolWeight: 1000,
    density: 1.31,
    colorCode: "11800",
    colorName: "Latte Brown",
    colorHex: "#D3B7A7",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Matte",
    spoolWeight: 1000,
    density: 1.31,
    colorCode: "11801",
    colorName: "Dark Brown",
    colorHex: "#7D6556",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Matte",
    spoolWeight: 1000,
    density: 1.31,
    colorCode: "11802",
    colorName: "Dark Chocolate",
    colorHex: "#4D3324",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Matte",
    spoolWeight: 1000,
    density: 1.31,
    colorCode: "11803",
    colorName: "Caramel",
    colorHex: "#AE835B",
  },

  // ── PLA Tough+ (12xxx) ───────────────────────────────────────────────────
  {
    brand: "Bambu Lab",
    material: "PLA Tough+",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "12100",
    colorName: "White",
    colorHex: "#f5f5f5",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Tough+",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "12101",
    colorName: "Black",
    colorHex: "#1a1a1a",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Tough+",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "12102",
    colorName: "Grey",
    colorHex: "#9e9e9e",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Tough+",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "12103",
    colorName: "Red",
    colorHex: "#e53935",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Tough+",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "12104",
    colorName: "Blue",
    colorHex: "#1e88e5",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Tough+",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "12105",
    colorName: "Green",
    colorHex: "#43a047",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Tough+",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "12106",
    colorName: "Yellow",
    colorHex: "#fdd835",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Tough+",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "12107",
    colorName: "Orange",
    colorHex: "#fb8c00",
  },

  // ── PLA Silk+ (13xxx) ────────────────────────────────────────────────────
  {
    brand: "Bambu Lab",
    material: "PLA Silk",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "13100",
    colorName: "Silk White",
    colorHex: "#F5F5F5",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Silk",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "13101",
    colorName: "Silk Silver",
    colorHex: "#C0C0C0",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Silk",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "13401",
    colorName: "Silk Gold",
    colorHex: "#FFD700",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Silk",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "13801",
    colorName: "Silk Copper",
    colorHex: "#B87333",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Silk",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "13200",
    colorName: "Silk Red",
    colorHex: "#D32F2F",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Silk",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "13201",
    colorName: "Silk Pink",
    colorHex: "#F48FB1",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Silk",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "13500",
    colorName: "Silk Green",
    colorHex: "#388E3C",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Silk",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "13600",
    colorName: "Silk Blue",
    colorHex: "#1976D2",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Silk",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "13700",
    colorName: "Silk Purple",
    colorHex: "#7B1FA2",
  },

  // ── PLA Metal (14xxx) ────────────────────────────────────────────────────

  {
    brand: "Bambu Lab",
    material: "PLA Metal",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "13103",
    colorName: "Iron Gray",
    colorHex: "#5C5C5C",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Metal",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "13402",
    colorName: "Iridium Gold",
    colorHex: "#CBA135",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Metal",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "13502",
    colorName: "Oxide Green",
    colorHex: "#455E45",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Metal",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "13602",
    colorName: "Cobalt Blue",
    colorHex: "#2A52BE",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Metal",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "13802",
    colorName: "Copper Brown",
    colorHex: "#8B5A2B",
  },

  // ── PLA Sparkle (15xxx) ────────────────────────────────────────────────────

  {
    brand: "Bambu Lab",
    material: "PLA Sparkle",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "10104",
    colorName: "Onyx Black",
    colorHex: "#1A1A1A",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Sparkle",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "10202",
    colorName: "Crimson Red",
    colorHex: "#A32020",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Sparkle",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "10602",
    colorName: "Cobalt Blue",
    colorHex: "#1C3573",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Sparkle",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "10502",
    colorName: "Emerald Green",
    colorHex: "#246B35",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Sparkle",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "10702",
    colorName: "Amethyst Purple",
    colorHex: "#523178",
  },

  // ── PLA Marble ────────────────────────────────────────────────────
  {
    brand: "Bambu Lab",
    material: "PLA Marble",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "10105",
    colorName: "Marble White",
    colorHex: "#EBEBEB",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Marble",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "10106",
    colorName: "Marble Gray",
    colorHex: "#9E9E9E",
  },

  // ── PLA Galaxy ────────────────────────────────────────────────────
  {
    brand: "Bambu Lab",
    material: "PLA Galaxy",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "1010A",
    colorName: "Nebula Black",
    colorHex: "#121212",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Galaxy",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "1010B",
    colorName: "Meteorite Gray",
    colorHex: "#595959",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Galaxy",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "1060A",
    colorName: "Glacier Blue",
    colorHex: "#4A708B",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Galaxy",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "1070A",
    colorName: "Amethyst Purple",
    colorHex: "#6A4B8C",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Glow",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "15500",
    colorName: "Glow Green",
    colorHex: "#A1FFAC",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Glow",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "15600",
    colorName: "Glow Blue",
    colorHex: "#7AC0E9",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Glow",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "15300",
    colorName: "Glow Orange",
    colorHex: "#FF9D5B",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Glow",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "15400",
    colorName: "Glow Yellow",
    colorHex: "#F8FF80",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Glow",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "15200",
    colorName: "Glow Pink",
    colorHex: "#FFB3D9",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Tough+",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "12107",
    colorName: "Tough+ White",
    colorHex: "#FAFAFA",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Tough+",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "12104",
    colorName: "Tough+ Black",
    colorHex: "#1A1A1A",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Tough+",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "12105",
    colorName: "Tough+ Gray",
    colorHex: "#8A8D8F",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Tough+",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "12106",
    colorName: "Tough+ Silver",
    colorHex: "#A2A5A4",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Tough+",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "12601",
    colorName: "Tough+ Cyan",
    colorHex: "#1F9EBA",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Tough+",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "12301",
    colorName: "Tough+ Orange",
    colorHex: "#ED712A",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Tough+",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "12401",
    colorName: "Tough+ Yellow",
    colorHex: "#F5C71A",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Aero",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "10100",
    colorName: "Aero White",
    colorHex: "#FAFAFA",
  },
  {
    brand: "Bambu Lab",
    material: "PLA Aero",
    spoolWeight: 1000,
    density: 1.24,
    colorCode: "10102",
    colorName: "Aero Gray",
    colorHex: "#8A8D8F",
  },
  {
    brand: "Bambu Lab",
    material: "PLA-CF",
    spoolWeight: 1000,
    density: 1.2,
    colorCode: "14100",
    colorName: "Black",
    colorHex: "#1C1C1C",
  },
  {
    brand: "Bambu Lab",
    material: "PLA-CF",
    spoolWeight: 1000,
    density: 1.2,
    colorCode: "14101",
    colorName: "Lava Gray",
    colorHex: "#4A4A4A",
  },
  {
    brand: "Bambu Lab",
    material: "PLA-CF",
    spoolWeight: 1000,
    density: 1.2,
    colorCode: "14200",
    colorName: "Burgundy Red",
    colorHex: "#6D242E",
  },
  {
    brand: "Bambu Lab",
    material: "PLA-CF",
    spoolWeight: 1000,
    density: 1.2,
    colorCode: "14500",
    colorName: "Matcha Green",
    colorHex: "#5C7852",
  },
  {
    brand: "Bambu Lab",
    material: "PLA-CF",
    spoolWeight: 1000,
    density: 1.2,
    colorCode: "14600",
    colorName: "Jeans Blue",
    colorHex: "#2C4A6B",
  },
  {
    brand: "Bambu Lab",
    material: "PLA-CF",
    spoolWeight: 1000,
    density: 1.2,
    colorCode: "14601",
    colorName: "Royal Blue",
    colorHex: "#1B3C73",
  },
  {
    brand: "Bambu Lab",
    material: "PLA-CF",
    spoolWeight: 1000,
    density: 1.2,
    colorCode: "14700",
    colorName: "Iris Purple",
    colorHex: "#5E466E",
  },
  {
    brand: "Bambu Lab",
    material: "PETG Basic",
    spoolWeight: 1000,
    density: 1.27,
    colorCode: "30100",
    colorName: "White",
    colorHex: "#FAFAFA",
  },
  {
    brand: "Bambu Lab",
    material: "PETG Basic",
    spoolWeight: 1000,
    density: 1.27,
    colorCode: "30101",
    colorName: "Black",
    colorHex: "#1A1A1A",
  },
  {
    brand: "Bambu Lab",
    material: "PETG Basic",
    spoolWeight: 1000,
    density: 1.27,
    colorCode: "30102",
    colorName: "Gray",
    colorHex: "#8A8D8F",
  },
  {
    brand: "Bambu Lab",
    material: "PETG Basic",
    spoolWeight: 1000,
    density: 1.27,
    colorCode: "30200",
    colorName: "Red",
    colorHex: "#C82B2B",
  },
  {
    brand: "Bambu Lab",
    material: "PETG Basic",
    spoolWeight: 1000,
    density: 1.27,
    colorCode: "30300",
    colorName: "Orange",
    colorHex: "#ED712A",
  },
  {
    brand: "Bambu Lab",
    material: "PETG Basic",
    spoolWeight: 1000,
    density: 1.27,
    colorCode: "30400",
    colorName: "Yellow",
    colorHex: "#F5C71A",
  },
  {
    brand: "Bambu Lab",
    material: "PETG Basic",
    spoolWeight: 1000,
    density: 1.27,
    colorCode: "30500",
    colorName: "Green",
    colorHex: "#00AE42",
  },
  {
    brand: "Bambu Lab",
    material: "PETG Basic",
    spoolWeight: 1000,
    density: 1.27,
    colorCode: "30600",
    colorName: "Blue",
    colorHex: "#2D4C8A",
  },
  {
    brand: "Bambu Lab",
    material: "PETG Basic",
    spoolWeight: 1000,
    density: 1.27,
    colorCode: "30700",
    colorName: "Purple",
    colorHex: "#724996",
  },
  {
    brand: "Bambu Lab",
    material: "PETG HF",
    spoolWeight: 1000,
    density: 1.27,
    colorCode: "33100",
    colorName: "White",
    colorHex: "#FFFFFF",
  },
  {
    brand: "Bambu Lab",
    material: "PETG HF",
    spoolWeight: 1000,
    density: 1.27,
    colorCode: "33101",
    colorName: "Gray",
    colorHex: "#ADB1B2",
  },
  {
    brand: "Bambu Lab",
    material: "PETG HF",
    spoolWeight: 1000,
    density: 1.27,
    colorCode: "33102",
    colorName: "Black",
    colorHex: "#000000",
  },
  {
    brand: "Bambu Lab",
    material: "PETG HF",
    spoolWeight: 1000,
    density: 1.27,
    colorCode: "33103",
    colorName: "Dark Gray",
    colorHex: "#515151",
  },
  {
    brand: "Bambu Lab",
    material: "PETG HF",
    spoolWeight: 1000,
    density: 1.27,
    colorCode: "33200",
    colorName: "Red",
    colorHex: "#EB3A3A",
  },
  {
    brand: "Bambu Lab",
    material: "PETG HF",
    spoolWeight: 1000,
    density: 1.27,
    colorCode: "33300",
    colorName: "Orange",
    colorHex: "#F75403",
  },
  {
    brand: "Bambu Lab",
    material: "PETG HF",
    spoolWeight: 1000,
    density: 1.27,
    colorCode: "33400",
    colorName: "Yellow",
    colorHex: "#FFD00B",
  },
  {
    brand: "Bambu Lab",
    material: "PETG HF",
    spoolWeight: 1000,
    density: 1.27,
    colorCode: "33401",
    colorName: "Cream",
    colorHex: "#F9DFB9",
  },
  {
    brand: "Bambu Lab",
    material: "PETG HF",
    spoolWeight: 1000,
    density: 1.27,
    colorCode: "33500",
    colorName: "Green",
    colorHex: "#00AE42",
  },
  {
    brand: "Bambu Lab",
    material: "PETG HF",
    spoolWeight: 1000,
    density: 1.27,
    colorCode: "33501",
    colorName: "Lime Green",
    colorHex: "#6EE53C",
  },
  {
    brand: "Bambu Lab",
    material: "PETG HF",
    spoolWeight: 1000,
    density: 1.27,
    colorCode: "33502",
    colorName: "Forest Green",
    colorHex: "#39541A",
  },
  {
    brand: "Bambu Lab",
    material: "PETG HF",
    spoolWeight: 1000,
    density: 1.27,
    colorCode: "33600",
    colorName: "Blue",
    colorHex: "#002E96",
  },
  {
    brand: "Bambu Lab",
    material: "PETG HF",
    spoolWeight: 1000,
    density: 1.27,
    colorCode: "33601",
    colorName: "Lake Blue",
    colorHex: "#1F79E5",
  },
  {
    brand: "Bambu Lab",
    material: "PETG HF",
    spoolWeight: 1000,
    density: 1.27,
    colorCode: "33801",
    colorName: "Peanut Brown",
    colorHex: "#875718",
  },
  {
    brand: "Bambu Lab",
    material: "PETG Translucent",
    spoolWeight: 1000,
    density: 1.27,
    colorCode: "32100",
    colorName: "Translucent Gray",
    colorHex: "#8E8E8E",
  },
  {
    brand: "Bambu Lab",
    material: "PETG Translucent",
    spoolWeight: 1000,
    density: 1.27,
    colorCode: "32600",
    colorName: "Translucent Light Blue",
    colorHex: "#61B0FF",
  },
  {
    brand: "Bambu Lab",
    material: "PETG Translucent",
    spoolWeight: 1000,
    density: 1.27,
    colorCode: "32101",
    colorName: "Clear",
    colorHex: "#FFFFFF",
  },
  {
    brand: "Bambu Lab",
    material: "PETG Translucent",
    spoolWeight: 1000,
    density: 1.27,
    colorCode: "32500",
    colorName: "Translucent Olive",
    colorHex: "#748C45",
  },
  {
    brand: "Bambu Lab",
    material: "PETG Translucent",
    spoolWeight: 1000,
    density: 1.27,
    colorCode: "32800",
    colorName: "Translucent Brown",
    colorHex: "#C9A381",
  },
  {
    brand: "Bambu Lab",
    material: "PETG Translucent",
    spoolWeight: 1000,
    density: 1.27,
    colorCode: "32501",
    colorName: "Translucent Teal",
    colorHex: "#77EDD7",
  },
  {
    brand: "Bambu Lab",
    material: "PETG Translucent",
    spoolWeight: 1000,
    density: 1.27,
    colorCode: "32300",
    colorName: "Translucent Orange",
    colorHex: "#FF911A",
  },
  {
    brand: "Bambu Lab",
    material: "PETG Translucent",
    spoolWeight: 1000,
    density: 1.27,
    colorCode: "32700",
    colorName: "Translucent Purple",
    colorHex: "#D6ABFF",
  },
  {
    brand: "Bambu Lab",
    material: "PETG Translucent",
    spoolWeight: 1000,
    density: 1.27,
    colorCode: "32200",
    colorName: "Translucent Pink",
    colorHex: "#F9C1BD",
  },
  {
    brand: "Bambu Lab",
    material: "PETG-CF",
    spoolWeight: 1000,
    density: 1.25,
    colorCode: "31100",
    colorName: "Black",
    colorHex: "#1C1C1C",
  },
  {
    brand: "Bambu Lab",
    material: "PETG-CF",
    spoolWeight: 1000,
    density: 1.25,
    colorCode: "31101",
    colorName: "Titan Gray",
    colorHex: "#4A4A4A",
  },
  {
    brand: "Bambu Lab",
    material: "PETG-CF",
    spoolWeight: 1000,
    density: 1.25,
    colorCode: "31200",
    colorName: "Brick Red",
    colorHex: "#8A3324",
  },
  {
    brand: "Bambu Lab",
    material: "PETG-CF",
    spoolWeight: 1000,
    density: 1.25,
    colorCode: "31500",
    colorName: "Malachite Green",
    colorHex: "#24523B",
  },
  {
    brand: "Bambu Lab",
    material: "PETG-CF",
    spoolWeight: 1000,
    density: 1.25,
    colorCode: "31600",
    colorName: "Indigo Blue",
    colorHex: "#2A4065",
  },
  {
    brand: "Bambu Lab",
    material: "PETG-CF",
    spoolWeight: 1000,
    density: 1.25,
    colorCode: "31700",
    colorName: "Violet Purple",
    colorHex: "#4E2F6D",
  },
  {
    brand: "Bambu Lab",
    material: "ABS",
    spoolWeight: 1000,
    density: 1.04,
    colorCode: "40100",
    colorName: "White",
    colorHex: "#FFFFFF",
  },
  {
    brand: "Bambu Lab",
    material: "ABS",
    spoolWeight: 1000,
    density: 1.04,
    colorCode: "40101",
    colorName: "Black",
    colorHex: "#000000",
  },
  {
    brand: "Bambu Lab",
    material: "ABS",
    spoolWeight: 1000,
    density: 1.04,
    colorCode: "40102",
    colorName: "Silver",
    colorHex: "#87909A",
  },
  {
    brand: "Bambu Lab",
    material: "ABS",
    spoolWeight: 1000,
    density: 1.04,
    colorCode: "40200",
    colorName: "Red",
    colorHex: "#D32941",
  },
  {
    brand: "Bambu Lab",
    material: "ABS",
    spoolWeight: 1000,
    density: 1.04,
    colorCode: "40300",
    colorName: "Orange",
    colorHex: "#FF6A13",
  },
  {
    brand: "Bambu Lab",
    material: "ABS",
    spoolWeight: 1000,
    density: 1.04,
    colorCode: "40400",
    colorName: "Yellow",
    colorHex: "#FCE900",
  },
  {
    brand: "Bambu Lab",
    material: "ABS",
    spoolWeight: 1000,
    density: 1.04,
    colorCode: "40401",
    colorName: "Beige",
    colorHex: "#DFD1A7",
  },
  {
    brand: "Bambu Lab",
    material: "ABS",
    spoolWeight: 1000,
    density: 1.04,
    colorCode: "40402",
    colorName: "Tangerine Yellow",
    colorHex: "#FFC72C",
  },
  {
    brand: "Bambu Lab",
    material: "ABS",
    spoolWeight: 1000,
    density: 1.04,
    colorCode: "40500",
    colorName: "Bambu Green",
    colorHex: "#00AE42",
  },
  {
    brand: "Bambu Lab",
    material: "ABS",
    spoolWeight: 1000,
    density: 1.04,
    colorCode: "40501",
    colorName: "Mint",
    colorHex: "#7AE1BF",
  },
  {
    brand: "Bambu Lab",
    material: "ABS",
    spoolWeight: 1000,
    density: 1.04,
    colorCode: "40502",
    colorName: "Olive",
    colorHex: "#789D4A",
  },
  {
    brand: "Bambu Lab",
    material: "ABS",
    spoolWeight: 1000,
    density: 1.04,
    colorCode: "40600",
    colorName: "Blue",
    colorHex: "#0A2CA5",
  },
  {
    brand: "Bambu Lab",
    material: "ABS",
    spoolWeight: 1000,
    density: 1.04,
    colorCode: "40601",
    colorName: "Azure",
    colorHex: "#489FDF",
  },
  {
    brand: "Bambu Lab",
    material: "ABS",
    spoolWeight: 1000,
    density: 1.04,
    colorCode: "40602",
    colorName: "Navy Blue",
    colorHex: "#0C2340",
  },
  {
    brand: "Bambu Lab",
    material: "ABS",
    spoolWeight: 1000,
    density: 1.04,
    colorCode: "40700",
    colorName: "Purple",
    colorHex: "#AF1685",
  },
  {
    brand: "Bambu Lab",
    material: "ABS",
    spoolWeight: 1000,
    density: 1.04,
    colorCode: "40701",
    colorName: "Lavender",
    colorHex: "#7248BD",
  },
  {
    brand: "Bambu Lab",
    material: "ABS-GF",
    spoolWeight: 1000,
    density: 1.08,
    colorCode: "41100",
    colorName: "White",
    colorHex: "#FFFFFF",
  },
  {
    brand: "Bambu Lab",
    material: "ABS-GF",
    spoolWeight: 1000,
    density: 1.08,
    colorCode: "41101",
    colorName: "Black",
    colorHex: "#000000",
  },
  {
    brand: "Bambu Lab",
    material: "ABS-GF",
    spoolWeight: 1000,
    density: 1.08,
    colorCode: "41102",
    colorName: "Gray",
    colorHex: "#C6C6C6",
  },
  {
    brand: "Bambu Lab",
    material: "ABS-GF",
    spoolWeight: 1000,
    density: 1.08,
    colorCode: "41200",
    colorName: "Red",
    colorHex: "#E83100",
  },
  {
    brand: "Bambu Lab",
    material: "ABS-GF",
    spoolWeight: 1000,
    density: 1.08,
    colorCode: "41300",
    colorName: "Orange",
    colorHex: "#F48438",
  },
  {
    brand: "Bambu Lab",
    material: "ABS-GF",
    spoolWeight: 1000,
    density: 1.08,
    colorCode: "41400",
    colorName: "Yellow",
    colorHex: "#FFE133",
  },
  {
    brand: "Bambu Lab",
    material: "ABS-GF",
    spoolWeight: 1000,
    density: 1.08,
    colorCode: "41500",
    colorName: "Green",
    colorHex: "#61BF36",
  },
  {
    brand: "Bambu Lab",
    material: "ABS-GF",
    spoolWeight: 1000,
    density: 1.08,
    colorCode: "41600",
    colorName: "Blue",
    colorHex: "#0C3B95",
  },
  {
    brand: "Bambu Lab",
    material: "ASA",
    spoolWeight: 1000,
    density: 1.07,
    colorCode: "45100",
    colorName: "White",
    colorHex: "#FFFAF2",
  },
  {
    brand: "Bambu Lab",
    material: "ASA",
    spoolWeight: 1000,
    density: 1.07,
    colorCode: "45101",
    colorName: "Black",
    colorHex: "#000000",
  },
  {
    brand: "Bambu Lab",
    material: "ASA",
    spoolWeight: 1000,
    density: 1.07,
    colorCode: "45102",
    colorName: "Gray",
    colorHex: "#8A949E",
  },
  {
    brand: "Bambu Lab",
    material: "ASA",
    spoolWeight: 1000,
    density: 1.07,
    colorCode: "45200",
    colorName: "Red",
    colorHex: "#E02928",
  },
  {
    brand: "Bambu Lab",
    material: "ASA",
    spoolWeight: 1000,
    density: 1.07,
    colorCode: "45500",
    colorName: "Green",
    colorHex: "#00A6A0",
  },
  {
    brand: "Bambu Lab",
    material: "ASA",
    spoolWeight: 1000,
    density: 1.07,
    colorCode: "45600",
    colorName: "Blue",
    colorHex: "#2140B4",
  },
  {
    brand: "Bambu Lab",
    material: "ASA-Aero",
    spoolWeight: 1000,
    density: 1.07,
    colorCode: "46100",
    colorName: "White",
    colorHex: "#F5F1DD",
  },
  {
    brand: "Bambu Lab",
    material: "TPU 95A",
    spoolWeight: 1000,
    density: 1.2,
    colorCode: "51100",
    colorName: "White",
    colorHex: "#FAFAFA",
  },
  {
    brand: "Bambu Lab",
    material: "TPU 95A",
    spoolWeight: 1000,
    density: 1.2,
    colorCode: "51101",
    colorName: "Black",
    colorHex: "#1A1A1A",
  },
  {
    brand: "Bambu Lab",
    material: "TPU 95A",
    spoolWeight: 1000,
    density: 1.2,
    colorCode: "51102",
    colorName: "Gray",
    colorHex: "#8A8D8F",
  },
  {
    brand: "Bambu Lab",
    material: "TPU 95A",
    spoolWeight: 1000,
    density: 1.2,
    colorCode: "51200",
    colorName: "Red",
    colorHex: "#C82B2B",
  },
  {
    brand: "Bambu Lab",
    material: "TPU 95A",
    spoolWeight: 1000,
    density: 1.2,
    colorCode: "51400",
    colorName: "Yellow",
    colorHex: "#F5C71A",
  },
  {
    brand: "Bambu Lab",
    material: "TPU 95A",
    spoolWeight: 1000,
    density: 1.2,
    colorCode: "51500",
    colorName: "Green",
    colorHex: "#00AE42",
  },
  {
    brand: "Bambu Lab",
    material: "TPU 95A",
    spoolWeight: 1000,
    density: 1.2,
    colorCode: "51600",
    colorName: "Blue",
    colorHex: "#2D4C8A",
  },
  {
    brand: "Bambu Lab",
    material: "TPU 95A HF",
    spoolWeight: 1000,
    density: 1.2,
    colorCode: "53100",
    colorName: "White",
    colorHex: "#FAFAFA",
  },
  {
    brand: "Bambu Lab",
    material: "TPU 95A HF",
    spoolWeight: 1000,
    density: 1.2,
    colorCode: "53101",
    colorName: "Black",
    colorHex: "#1A1A1A",
  },
  {
    brand: "Bambu Lab",
    material: "TPU 95A HF",
    spoolWeight: 1000,
    density: 1.2,
    colorCode: "53102",
    colorName: "Gray",
    colorHex: "#8A8D8F",
  },
  {
    brand: "Bambu Lab",
    material: "TPU 95A HF",
    spoolWeight: 1000,
    density: 1.2,
    colorCode: "53200",
    colorName: "Red",
    colorHex: "#C82B2B",
  },
  {
    brand: "Bambu Lab",
    material: "TPU 95A HF",
    spoolWeight: 1000,
    density: 1.2,
    colorCode: "53300",
    colorName: "Orange",
    colorHex: "#ED712A",
  },
  {
    brand: "Bambu Lab",
    material: "TPU 95A HF",
    spoolWeight: 1000,
    density: 1.2,
    colorCode: "53400",
    colorName: "Yellow",
    colorHex: "#F5C71A",
  },
  {
    brand: "Bambu Lab",
    material: "TPU 95A HF",
    spoolWeight: 1000,
    density: 1.2,
    colorCode: "53500",
    colorName: "Green",
    colorHex: "#00AE42",
  },
  {
    brand: "Bambu Lab",
    material: "TPU 95A HF",
    spoolWeight: 1000,
    density: 1.2,
    colorCode: "53600",
    colorName: "Blue",
    colorHex: "#2D4C8A",
  },
  {
    brand: "Bambu Lab",
    material: "PC",
    spoolWeight: 1000,
    density: 1.18,
    colorCode: "42100",
    colorName: "White",
    colorHex: "#FAFAFA",
  },
  {
    brand: "Bambu Lab",
    material: "PC",
    spoolWeight: 1000,
    density: 1.18,
    colorCode: "42101",
    colorName: "Black",
    colorHex: "#1A1A1A",
  },
  {
    brand: "Bambu Lab",
    material: "PC",
    spoolWeight: 1000,
    density: 1.18,
    colorCode: "42102",
    colorName: "Transparent",
    colorHex: "#FFFFFF",
  },
  {
    brand: "Bambu Lab",
    material: "PET-CF",
    spoolWeight: 1000,
    density: 1.3,
    colorCode: "35100",
    colorName: "Black",
    colorHex: "#1A1A1A",
  },
  {
    brand: "Bambu Lab",
    material: "PET-CF",
    spoolWeight: 1000,
    density: 1.3,
    colorCode: "35102",
    colorName: "Gray",
    colorHex: "#8A8D8F",
  },
  {
    brand: "Bambu Lab",
    material: "PET-CF",
    spoolWeight: 1000,
    density: 1.3,
    colorCode: "35200",
    colorName: "Red",
    colorHex: "#C82B2B",
  },
  {
    brand: "Bambu Lab",
    material: "PET-CF",
    spoolWeight: 1000,
    density: 1.3,
    colorCode: "35400",
    colorName: "Yellow",
    colorHex: "#F5C71A",
  },
  {
    brand: "Bambu Lab",
    material: "PET-CF",
    spoolWeight: 1000,
    density: 1.3,
    colorCode: "35600",
    colorName: "Blue",
    colorHex: "#2D4C8A",
  },
  {
    brand: "Bambu Lab",
    material: "PAHT-CF",
    spoolWeight: 1000,
    density: 1.06,
    colorCode: "70100",
    colorName: "Black",
    colorHex: "#1A1A1A",
  },
  {
    brand: "Bambu Lab",
    material: "PA6-CF",
    spoolWeight: 1000,
    density: 1.09,
    colorCode: "72100",
    colorName: "Black",
    colorHex: "#1A1A1A",
  },
  {
    brand: "Bambu Lab",
    material: "PA-GF",
    spoolWeight: 1000,
    density: 1.15,
    colorCode: "72102",
    colorName: "White",
    colorHex: "#EAEAE4",
  },
  {
    brand: "Bambu Lab",
    material: "PA-GF",
    spoolWeight: 1000,
    density: 1.15,
    colorCode: "72104",
    colorName: "Black",
    colorHex: "#000000",
  },
  {
    brand: "Bambu Lab",
    material: "PA-GF",
    spoolWeight: 1000,
    density: 1.15,
    colorCode: "72103",
    colorName: "Gray",
    colorHex: "#353533",
  },
  {
    brand: "Bambu Lab",
    material: "PA-GF",
    spoolWeight: 1000,
    density: 1.15,
    colorCode: "72600",
    colorName: "Blue",
    colorHex: "#75AED8",
  },
  {
    brand: "Bambu Lab",
    material: "PA-GF",
    spoolWeight: 1000,
    density: 1.15,
    colorCode: "72200",
    colorName: "Orange",
    colorHex: "#FF4800",
  },
  {
    brand: "Bambu Lab",
    material: "PA-GF",
    spoolWeight: 1000,
    density: 1.15,
    colorCode: "72400",
    colorName: "Yellow",
    colorHex: "#FFCE00",
  },
  {
    brand: "Bambu Lab",
    material: "PA-GF",
    spoolWeight: 1000,
    density: 1.15,
    colorCode: "72500",
    colorName: "Lime",
    colorHex: "#C5ED48",
  },
  {
    brand: "Bambu Lab",
    material: "PA-GF",
    spoolWeight: 1000,
    density: 1.15,
    colorCode: "72800",
    colorName: "Brown",
    colorHex: "#5B492F",
  },
  {
    brand: "Bambu Lab",
    material: "PPA-CF",
    spoolWeight: 750,
    density: 1.25,
    colorCode: "73100",
    colorName: "Black",
    colorHex: "#1A1A1A",
  },
  {
    brand: "Bambu Lab",
    material: "PPA-GF",
    spoolWeight: 750,
    density: 1.16,
    colorCode: "",
    colorName: "Black",
    colorHex: "#1A1A1A",
  },
  {
    brand: "Bambu Lab",
    material: "PPS-CF",
    spoolWeight: 1000,
    density: 1.34,
    colorCode: "73100",
    colorName: "Black",
    colorHex: "#1A1A1A",
  },
  {
    brand: "Bambu Lab",
    material: "Support for PLA",
    spoolWeight: 500,
    density: 1.33,
    colorCode: "65100",
    colorName: "White",
    colorHex: "#FAFAFA",
  },
  {
    brand: "Bambu Lab",
    material: "Support for PA/PET",
    spoolWeight: 500,
    density: 1.15,
    colorCode: "66100",
    colorName: "White",
    colorHex: "#FAFAFA",
  },
  {
    brand: "Bambu Lab",
    material: "Support for ABS/ASA/PC",
    spoolWeight: 500,
    density: 1.05,
    colorCode: "",
    colorName: "White",
    colorHex: "#FAFAFA",
  },
  {
    brand: "Bambu Lab",
    material: "PVA",
    spoolWeight: 500,
    density: 1.19,
    colorCode: "62100",
    colorName: "Natural",
    colorHex: "#E8E9E1",
  },
];

// ─── Cores genéricas para outras marcas (sem código) ─────────────────────────

interface ColorEntry {
  name: string;
  hex: string;
}

const defaultColors: ColorEntry[] = [
  { name: "Black", hex: "#1a1a1a" },
  { name: "White", hex: "#f5f5f5" },
  { name: "Grey", hex: "#9e9e9e" },
  { name: "Red", hex: "#e53935" },
  { name: "Blue", hex: "#1e88e5" },
  { name: "Green", hex: "#43a047" },
  { name: "Yellow", hex: "#fdd835" },
  { name: "Orange", hex: "#fb8c00" },
  { name: "Purple", hex: "#8e24aa" },
  { name: "Pink", hex: "#e91e63" },
  { name: "Brown", hex: "#6d4c41" },
  { name: "Transparent", hex: "#e0f7fa" },
];

// Catálogo para marcas sem códigos individuais — combinado com defaultColors
const catalog: {
  brand: string;
  material: string;
  spoolWeight: number;
  density?: number;
}[] = [
  // ── Polymaker ─────────────────────────────────────────────────────────────
  {
    brand: "Polymaker",
    material: "PolyLite PLA",
    spoolWeight: 1000,
    density: 1.24,
  },
  {
    brand: "Polymaker",
    material: "PolyMax PLA",
    spoolWeight: 750,
    density: 1.24,
  },
  {
    brand: "Polymaker",
    material: "PolyLite PETG",
    spoolWeight: 1000,
    density: 1.27,
  },
  {
    brand: "Polymaker",
    material: "PolyLite ABS",
    spoolWeight: 1000,
    density: 1.04,
  },
  {
    brand: "Polymaker",
    material: "PolyLite ASA",
    spoolWeight: 1000,
    density: 1.07,
  },
  {
    brand: "Polymaker",
    material: "PolyFlex TPU95",
    spoolWeight: 750,
    density: 1.21,
  },
  { brand: "Polymaker", material: "PA6-GF", spoolWeight: 500, density: 1.18 },

  // ── Prusament ─────────────────────────────────────────────────────────────
  { brand: "Prusament", material: "PLA", spoolWeight: 1000, density: 1.24 },
  { brand: "Prusament", material: "PETG", spoolWeight: 1000, density: 1.27 },
  { brand: "Prusament", material: "ASA", spoolWeight: 850, density: 1.07 },
  {
    brand: "Prusament",
    material: "PLA Blend",
    spoolWeight: 1000,
    density: 1.24,
  },
  {
    brand: "Prusament",
    material: "PETG Carbon Fiber",
    spoolWeight: 500,
    density: 1.3,
  },

  // ── eSUN ──────────────────────────────────────────────────────────────────
  { brand: "eSUN", material: "PLA+", spoolWeight: 1000, density: 1.24 },
  { brand: "eSUN", material: "PETG", spoolWeight: 1000, density: 1.27 },
  { brand: "eSUN", material: "ABS+", spoolWeight: 1000, density: 1.04 },
  { brand: "eSUN", material: "eTPU-95A", spoolWeight: 1000, density: 1.21 },
  { brand: "eSUN", material: "eASA", spoolWeight: 1000, density: 1.07 },
  { brand: "eSUN", material: "PLA-CF", spoolWeight: 500, density: 1.3 },

  // ── Fillamentum ───────────────────────────────────────────────────────────
  {
    brand: "Fillamentum",
    material: "PLA Extrafill",
    spoolWeight: 750,
    density: 1.24,
  },
  {
    brand: "Fillamentum",
    material: "PETG Extrafill",
    spoolWeight: 750,
    density: 1.27,
  },
  {
    brand: "Fillamentum",
    material: "ASA Extrafill",
    spoolWeight: 750,
    density: 1.07,
  },
  {
    brand: "Fillamentum",
    material: "ABS Extrafill",
    spoolWeight: 750,
    density: 1.04,
  },
  {
    brand: "Fillamentum",
    material: "Flexfill TPU 98A",
    spoolWeight: 500,
    density: 1.22,
  },

  // ── Fiberlogy ─────────────────────────────────────────────────────────────
  { brand: "Fiberlogy", material: "Easy PLA", spoolWeight: 850, density: 1.24 },
  { brand: "Fiberlogy", material: "PETG", spoolWeight: 850, density: 1.27 },
  {
    brand: "Fiberlogy",
    material: "NYLON PA12",
    spoolWeight: 500,
    density: 1.01,
  },
  {
    brand: "Fiberlogy",
    material: "FiberSmooth",
    spoolWeight: 850,
    density: 1.24,
  },
  {
    brand: "Fiberlogy",
    material: "FIBERFLEX 40D",
    spoolWeight: 500,
    density: 1.2,
  },
];

// ─── Presets de Impressoras ───────────────────────────────────────────────────

const PRINTER_PRESETS: {
  name: string;
  brand: string;
  model: string;
  extrusionType: string;
  multiMaterialSlots: number;
  powerWatts: number;
  hourlyCost: number;
  maintenanceTasks: { taskName: string; intervalHours: number }[];
}[] = [
  // ── Creality ──────────────────────────────────────────────────────────────
  {
    name: "Creality Ender 3",
    brand: "Creality",
    model: "Ender 3",
    extrusionType: "Bowden",
    multiMaterialSlots: 1,
    powerWatts: 270,
    hourlyCost: 0.05,
    maintenanceTasks: [
      { taskName: "Lubrificar eixos X/Y/Z", intervalHours: 200 },
      { taskName: "Verificar tensão das correias", intervalHours: 100 },
      { taskName: "Limpar tubo PTFE (Bowden)", intervalHours: 150 },
      { taskName: "Nivelar cama manualmente", intervalHours: 50 },
    ],
  },
  {
    name: "Creality CR-10",
    brand: "Creality",
    model: "CR-10",
    extrusionType: "Bowden",
    multiMaterialSlots: 1,
    powerWatts: 350,
    hourlyCost: 0.06,
    maintenanceTasks: [
      { taskName: "Lubrificar eixos X/Y/Z", intervalHours: 200 },
      { taskName: "Verificar tensão das correias", intervalHours: 100 },
      { taskName: "Limpar tubo PTFE (Bowden)", intervalHours: 200 },
      { taskName: "Inspecionar cama de vidro", intervalHours: 100 },
    ],
  },
  {
    name: "Creality K1",
    brand: "Creality",
    model: "K1",
    extrusionType: "Direct",
    multiMaterialSlots: 1,
    powerWatts: 1000,
    hourlyCost: 0.12,
    maintenanceTasks: [
      { taskName: "Lubrificar guias lineares", intervalHours: 300 },
      { taskName: "Limpar extrusora direta", intervalHours: 200 },
      { taskName: "Verificar ventoinhas de arrefecimento", intervalHours: 500 },
      { taskName: "Calibrar input shaping", intervalHours: 500 },
    ],
  },

  // ── Bambu Lab ─────────────────────────────────────────────────────────────
  {
    name: "Bambu Lab P1S",
    brand: "Bambu Lab",
    model: "P1S",
    extrusionType: "Direct",
    multiMaterialSlots: 20, // suporta até 5 AMS × 4 slots
    powerWatts: 1000,
    hourlyCost: 0.15,
    maintenanceTasks: [
      { taskName: "Lubrificar eixos e guias", intervalHours: 300 },
      { taskName: "Limpar AMS (sensores e roletes)", intervalHours: 200 },
      { taskName: "Verificar filtro de carbono ativo", intervalHours: 500 },
      { taskName: "Limpar sensor de cama", intervalHours: 200 },
      { taskName: "Atualizar firmware", intervalHours: 500 },
    ],
  },
  {
    name: "Bambu Lab X1C",
    brand: "Bambu Lab",
    model: "X1C",
    extrusionType: "Direct",
    multiMaterialSlots: 20,
    powerWatts: 1400,
    hourlyCost: 0.18,
    maintenanceTasks: [
      { taskName: "Lubrificar guias lineares de carbono", intervalHours: 300 },
      { taskName: "Limpar AMS (sensores e roletes)", intervalHours: 200 },
      { taskName: "Verificar filtro de carbono ativo", intervalHours: 500 },
      { taskName: "Limpar lente do LiDAR", intervalHours: 100 },
      { taskName: "Inspecionar nozzle de aço endurecido", intervalHours: 400 },
      { taskName: "Atualizar firmware", intervalHours: 500 },
    ],
  },
  {
    name: "Bambu Lab A1",
    brand: "Bambu Lab",
    model: "A1",
    extrusionType: "Direct",
    multiMaterialSlots: 20,
    powerWatts: 1000,
    hourlyCost: 0.12,
    maintenanceTasks: [
      { taskName: "Lubrificar eixos", intervalHours: 300 },
      { taskName: "Limpar AMS Lite", intervalHours: 200 },
      { taskName: "Verificar tensão das correias", intervalHours: 200 },
      { taskName: "Atualizar firmware", intervalHours: 500 },
    ],
  },

  // ── Prusa ─────────────────────────────────────────────────────────────────
  {
    name: "Prusa MK4",
    brand: "Prusa",
    model: "MK4",
    extrusionType: "Direct",
    multiMaterialSlots: 5, // com MMU3
    powerWatts: 240,
    hourlyCost: 0.08,
    maintenanceTasks: [
      { taskName: "Lubrificar varões lisos e fuso Z", intervalHours: 200 },
      { taskName: "Verificar tensão correia X/Y", intervalHours: 150 },
      { taskName: "Limpar extrusora Nextruder", intervalHours: 300 },
      { taskName: "Inspecionar PEI sheet", intervalHours: 100 },
      { taskName: "Verificar loadcell (sensor de cama)", intervalHours: 300 },
    ],
  },
  {
    name: "Prusa Mini+",
    brand: "Prusa",
    model: "Mini+",
    extrusionType: "Bowden",
    multiMaterialSlots: 1,
    powerWatts: 180,
    hourlyCost: 0.05,
    maintenanceTasks: [
      { taskName: "Lubrificar varões e fuso Z", intervalHours: 200 },
      { taskName: "Verificar tensão das correias", intervalHours: 150 },
      { taskName: "Limpar tubo PTFE (Bowden)", intervalHours: 200 },
      { taskName: "Inspecionar PEI sheet", intervalHours: 100 },
    ],
  },

  // ── Voron ─────────────────────────────────────────────────────────────────
  {
    name: "Voron 2.4",
    brand: "Voron",
    model: "2.4",
    extrusionType: "Direct",
    multiMaterialSlots: 12, // com ERCF
    powerWatts: 800,
    hourlyCost: 0.1,
    maintenanceTasks: [
      { taskName: "Lubrificar guias lineares (MGN)", intervalHours: 200 },
      { taskName: "Verificar tensão correias X/Y/AB", intervalHours: 100 },
      { taskName: "Inspecionar parafusos Z (quad gantry)", intervalHours: 150 },
      { taskName: "Limpar extrusora (Stealthburner)", intervalHours: 300 },
      { taskName: "Verificar cabos e ligações (CAN bus)", intervalHours: 300 },
      { taskName: "Calibrar QGL (Quad Gantry Leveling)", intervalHours: 200 },
    ],
  },
  {
    name: "Voron Trident",
    brand: "Voron",
    model: "Trident",
    extrusionType: "Direct",
    multiMaterialSlots: 12,
    powerWatts: 700,
    hourlyCost: 0.09,
    maintenanceTasks: [
      { taskName: "Lubrificar guias lineares (MGN)", intervalHours: 200 },
      { taskName: "Verificar tensão correias X/Y", intervalHours: 100 },
      { taskName: "Inspecionar parafusos Z (3 pontos)", intervalHours: 150 },
      { taskName: "Limpar extrusora (Stealthburner)", intervalHours: 300 },
      { taskName: "Calibrar Z-tilt", intervalHours: 200 },
    ],
  },
  {
    name: "Voron 0.2",
    brand: "Voron",
    model: "0.2",
    extrusionType: "Direct",
    multiMaterialSlots: 1,
    powerWatts: 250,
    hourlyCost: 0.06,
    maintenanceTasks: [
      { taskName: "Lubrificar guias lineares", intervalHours: 200 },
      { taskName: "Verificar tensão correias", intervalHours: 100 },
      { taskName: "Limpar extrusora (Mini Stealthburner)", intervalHours: 300 },
    ],
  },

  // ── AnkerMake ─────────────────────────────────────────────────────────────
  {
    name: "AnkerMake M5",
    brand: "AnkerMake",
    model: "M5",
    extrusionType: "Direct",
    multiMaterialSlots: 1,
    powerWatts: 350,
    hourlyCost: 0.08,
    maintenanceTasks: [
      { taskName: "Lubrificar eixos e guias", intervalHours: 200 },
      { taskName: "Verificar tensão das correias", intervalHours: 150 },
      { taskName: "Limpar extrusora", intervalHours: 200 },
      { taskName: "Verificar câmara de monitorização", intervalHours: 300 },
    ],
  },
  {
    name: "AnkerMake M5C",
    brand: "AnkerMake",
    model: "M5C",
    extrusionType: "Direct",
    multiMaterialSlots: 1,
    powerWatts: 300,
    hourlyCost: 0.07,
    maintenanceTasks: [
      { taskName: "Lubrificar eixos e guias", intervalHours: 200 },
      { taskName: "Verificar tensão das correias", intervalHours: 150 },
      { taskName: "Limpar extrusora direta", intervalHours: 200 },
    ],
  },
];

// ─── Presets de Unidades de Expansão ─────────────────────────────────────────

const UNIT_PRESETS: {
  name: string;
  brand: string;
  slotCount: number;
  supportsHighTemp: boolean;
  supportsAbrasive: boolean;
  notes?: string;
}[] = [
  // ── Bambu Lab ─────────────────────────────────────────────────────────────
  {
    name: "AMS 2 Pro",
    brand: "Bambu Lab",
    slotCount: 4,
    supportsHighTemp: false,
    supportsAbrasive: false,
    notes:
      "Suporta PLA, PETG, ABS, ASA, TPU. Não recomendado para PA-CF ou materiais abrasivos.",
  },
  {
    name: "AMS HT",
    brand: "Bambu Lab",
    slotCount: 1,
    supportsHighTemp: true,
    supportsAbrasive: true,
    notes:
      "Projetado para materiais de engenharia: PA-CF, PET-CF, PEI. Alta temperatura e abrasivos.",
  },
  {
    name: "AMS Lite",
    brand: "Bambu Lab",
    slotCount: 4,
    supportsHighTemp: false,
    supportsAbrasive: false,
    notes:
      "Versão simplificada do AMS. Suporta PLA e materiais básicos. Exclusivo para A1 e A1 Mini.",
  },

  // ── Prusa ─────────────────────────────────────────────────────────────────
  {
    name: "MMU3",
    brand: "Prusa",
    slotCount: 5,
    supportsHighTemp: false,
    supportsAbrasive: false,
    notes:
      "Multi Material Upgrade 3. Compatível com MK4 e MK3.9. 5 filamentos simultâneos.",
  },

  // ── Voron / Comunidade ────────────────────────────────────────────────────
  {
    name: "ERCF v2 (8T)",
    brand: "Voron / Comunidade",
    slotCount: 8,
    supportsHighTemp: false,
    supportsAbrasive: false,
    notes:
      "Enraged Rabbit Carrot Feeder v2, configuração de 8 canais. Open source.",
  },
  {
    name: "ERCF v2 (12T)",
    brand: "Voron / Comunidade",
    slotCount: 12,
    supportsHighTemp: false,
    supportsAbrasive: false,
    notes:
      "Enraged Rabbit Carrot Feeder v2, configuração de 12 canais. Open source.",
  },
  {
    name: "Tradrack (8T)",
    brand: "Voron / Comunidade",
    slotCount: 8,
    supportsHighTemp: false,
    supportsAbrasive: false,
    notes: "Alternativa ao ERCF. Mais simples de montar, 8 canais.",
  },

  // ── Mosaic ────────────────────────────────────────────────────────────────
  {
    name: "Palette 3",
    brand: "Mosaic Manufacturing",
    slotCount: 4,
    supportsHighTemp: false,
    supportsAbrasive: false,
    notes:
      "Compatível com qualquer impressora FDM. Combina 4 filamentos numa única extrusão.",
  },
  {
    name: "Palette 3 Pro",
    brand: "Mosaic Manufacturing",
    slotCount: 8,
    supportsHighTemp: true,
    supportsAbrasive: false,
    notes: "Versão Pro com 8 canais e suporte a materiais de alta temperatura.",
  },
];

// ─── Setup Prisma ─────────────────────────────────────────────────────────────

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  // ── 1. GlobalFilament ──────────────────────────────────────────────────────
  console.log("🌱 A fazer seed do catálogo de filamentos...");

  await prisma.globalFilament.deleteMany();

  // Entradas Bambu Lab (explícitas, com código por SKU)
  const bambuCount = bambuEntries.length;

  // Entradas restantes (combinação material × defaultColors)
  const otherEntries: typeof bambuEntries = [];
  for (const item of catalog) {
    for (const color of defaultColors) {
      otherEntries.push({
        brand: item.brand,
        material: item.material,
        colorName: color.name,
        colorHex: color.hex,
        spoolWeight: item.spoolWeight,
        density: item.density,
      });
    }
  }

  const entries = [...bambuEntries, ...otherEntries];

  await prisma.globalFilament.createMany({ data: entries });
  console.log(
    `✅ ${entries.length} filamentos criados (${bambuCount} Bambu Lab com código + ${otherEntries.length} outras marcas)\n`,
  );

  // ── 2. PrinterPresets ──────────────────────────────────────────────────────
  console.log("🖨️  A fazer seed dos presets de impressoras...");

  await prisma.printerPreset.deleteMany({ where: { isGlobal: true } });

  for (const preset of PRINTER_PRESETS) {
    const { maintenanceTasks, ...presetData } = preset;

    const created = await prisma.printerPreset.create({
      data: {
        ...presetData,
        isGlobal: true,
        userId: null,
        maintenanceTasks: {
          create: maintenanceTasks,
        },
      },
    });

    console.log(
      `  ✅ ${created.brand} ${created.model} — ${maintenanceTasks.length} tarefas de manutenção`,
    );
  }

  console.log(
    `\n✅ ${PRINTER_PRESETS.length} presets de impressoras criados.\n`,
  );

  // ── 3. UnitPresets ────────────────────────────────────────────────────────
  console.log("🔧 A fazer seed do catálogo de unidades de expansão...");

  await prisma.unitPreset.deleteMany({ where: { isGlobal: true } });

  await prisma.unitPreset.createMany({
    data: UNIT_PRESETS.map((u) => ({ ...u, isGlobal: true })),
  });

  for (const u of UNIT_PRESETS) {
    console.log(
      `  ✅ ${u.brand} ${u.name} — ${u.slotCount} slots${u.supportsHighTemp ? " · alta temp" : ""}${u.supportsAbrasive ? " · abrasivos" : ""}`,
    );
  }

  console.log(
    `\n✨ Seed concluído: ${UNIT_PRESETS.length} unidades de expansão criadas.`,
  );
}

main()
  .catch((e) => {
    console.error("❌ Erro no Seed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
